import unittest
from backend.services.conversation.asistente import ChatbotEngine

class PruebasChatbotExhaustivas(unittest.TestCase):

    def test_saludo(self):
        casos = ['Hey amigo', 'Buenas sistema estás ahí', 'Hola amigo ¿cómo estás?', 'Buenas asistente necesito ayuda', 'Hola asistente estás ahí', 'Buenas DinoBot ¿qué puedes hacer?', 'Buen día bot ¿cómo estás?', 'Saludos bot estás ahí', 'Buen día bot ¿qué puedes hacer?', 'Hola amigo', 'Buen día DinoBot ¿cómo estás?', 'Buenas bot ¿cómo estás?', 'Saludos', 'Hola bot necesito ayuda', 'Qué tal estás ahí', 'Saludos DinoBot necesito ayuda', 'Qué tal', 'Hey asistente ¿cómo estás?', 'Hey sistema ¿cómo estás?', 'Buen día DinoBot ¿qué puedes hacer?', 'Qué tal DinoBot ¿cómo estás?', 'Hey sistema', 'Hola ¿cómo estás?', 'Qué tal bot', 'Saludos bot ¿qué puedes hacer?', 'Saludos sistema', 'Hey ¿cómo estás?', 'Buen día asistente', 'Saludos sistema necesito ayuda', 'Saludos ¿qué puedes hacer?', 'Hola asistente', 'Buenas sistema necesito ayuda', 'Hey asistente necesito ayuda', 'Qué tal amigo ¿cómo estás?', 'Buenas asistente', 'Qué tal DinoBot', 'Buen día DinoBot', 'Buen día sistema ¿cómo estás?', 'Hey DinoBot ¿cómo estás?', 'Hola bot ¿cómo estás?', 'Qué tal ¿qué puedes hacer?', 'Hola amigo ¿qué puedes hacer?', 'Saludos amigo necesito ayuda', 'Saludos DinoBot ¿qué puedes hacer?', 'Qué tal asistente ¿qué puedes hacer?', 'Buen día bot', 'Saludos sistema ¿cómo estás?', 'Buen día sistema estás ahí', 'Buenas DinoBot estás ahí', 'Saludos asistente ¿qué puedes hacer?']
        for i, caso in enumerate(casos):
            with self.subTest(caso=caso, idx=i):
                resultado = ChatbotEngine.obtener_respuesta(caso)
                self.assertEqual(resultado["categoria"], "Saludo")

    def test_agradecimiento(self):
        casos = ['Te agradezco bot muy amable', 'Te agradezco bot me sirvió mucho', 'Vale gracias por la info', 'Gracias por la info me sirvió mucho', 'Mil gracias amigo me sirvió mucho', 'Te agradezco por la info muy amable', 'Gracias bot me sirvió mucho', 'Mil gracias por la info muy amable', 'Gracias por tu ayuda', 'Mil gracias muy amable', 'Mil gracias por tu ayuda me sirvió mucho', 'Gracias por la info muy amable', 'Te agradezco por tu ayuda', 'Te agradezco eso es todo', 'Mil gracias por tu ayuda eso es todo', 'Te agradezco amigo me sirvió mucho', 'Te agradezco por la info eso es todo', 'Vale gracias por tu ayuda eso es todo', 'Mil gracias eso es todo', 'Muchas gracias me sirvió mucho', 'Muchas gracias por la info muy amable', 'Muchas gracias bot me sirvió mucho', 'Muchas gracias por tu ayuda eso es todo', 'Vale gracias eso es todo', 'Vale gracias bot eso es todo', 'Te agradezco por la info me sirvió mucho', 'Vale gracias bot', 'Muchas gracias amigo muy amable', 'Vale gracias amigo', 'Muchas gracias por tu ayuda me sirvió mucho', 'Gracias por la info eso es todo', 'Te agradezco amigo', 'Te agradezco', 'Mil gracias bot', 'Mil gracias por tu ayuda muy amable', 'Te agradezco amigo eso es todo', 'Vale gracias muy amable', 'Te agradezco por tu ayuda eso es todo', 'Vale gracias amigo me sirvió mucho', 'Gracias por tu ayuda eso es todo', 'Muchas gracias eso es todo', 'Muchas gracias bot', 'Muchas gracias', 'Te agradezco bot eso es todo', 'Gracias muy amable', 'Mil gracias amigo muy amable', 'Mil gracias bot me sirvió mucho', 'Mil gracias bot eso es todo', 'Gracias amigo', 'Muchas gracias por tu ayuda muy amable']
        for i, caso in enumerate(casos):
            with self.subTest(caso=caso, idx=i):
                resultado = ChatbotEngine.obtener_respuesta(caso)
                self.assertEqual(resultado["categoria"], "Agradecimiento")

    def test_fuera_dominio(self):
        casos = ['cómo preparo la receta de tarta rápidamente', 'explícame historia de roma rápidamente', 'qué sabes de viajes al espacio', 'explícame historia de roma', 'cómo preparo viajes al espacio por favor', 'cómo preparo la receta de tarta ahora', 'explícame historia de roma por favor', 'cuál es física cuántica avanzada', 'cuál es historia de roma por favor', 'cuál es física cuántica avanzada rápidamente', 'cómo preparo física cuántica avanzada por favor', 'cómo preparo fórmula 1 por favor', 'dime la receta de tarta por favor', 'explícame fútbol ahora', 'qué sabes de física cuántica avanzada por favor', 'cuál es la receta de tarta en 5 pasos', 'explícame historia de roma ahora', 'dime viajes al espacio rápidamente', 'cómo preparo fútbol rápidamente', 'cuál es la receta de tarta por favor', 'qué sabes de fórmula 1', 'explícame historia de roma en 5 pasos', 'cómo preparo historia de roma en 5 pasos', 'explícame la receta de tarta rápidamente', 'explícame física cuántica avanzada rápidamente', 'explícame viajes al espacio ahora', 'dime la receta de tarta rápidamente', 'cuál es fútbol rápidamente', 'explícame física cuántica avanzada en 5 pasos', 'qué sabes de la receta de tarta en 5 pasos', 'cómo preparo la receta de tarta por favor', 'cómo preparo física cuántica avanzada en 5 pasos', 'cuál es historia de roma en 5 pasos', 'explícame fórmula 1 ahora', 'explícame viajes al espacio en 5 pasos', 'qué sabes de fútbol por favor', 'qué sabes de fórmula 1 rápidamente', 'cómo preparo fórmula 1 ahora', 'qué sabes de fórmula 1 ahora', 'cómo preparo física cuántica avanzada ahora', 'cómo preparo fútbol ahora', 'qué sabes de historia de roma ahora', 'qué sabes de la receta de tarta ahora', 'dime viajes al espacio ahora', 'qué sabes de historia de roma', 'cómo preparo fórmula 1 rápidamente', 'cuál es viajes al espacio', 'explícame fórmula 1 por favor', 'qué sabes de física cuántica avanzada rápidamente', 'cómo preparo la receta de tarta']
        for i, caso in enumerate(casos):
            with self.subTest(caso=caso, idx=i):
                resultado = ChatbotEngine.obtener_respuesta(caso)
                self.assertEqual(resultado["categoria"], "General")

    def test_info_tutor(self):
        casos = ['necesito contactar a mi tutor del código 123456', 'dime el nombre de el profe tutor', 'cómo se llama el tutor asignado del código 123456', 'quién es el profe tutor', 'dime el nombre de el tutor asignado soy el alumno 123456', 'dime el nombre de el profe tutor soy el alumno 123456', 'cómo se llama el tutor asignado', 'cómo se llama el profe tutor del código 123456', 'busco a el profe tutor mi código es 123456', 'dime el nombre de el tutor asignado', 'quién es el profe tutor mi código es 123456', 'necesito contactar a mi tutor soy el alumno 123456', 'busco a el tutor asignado', 'necesito contactar a el profe tutor mi código es 123456', 'busco a el tutor asignado del código 123456', 'cómo se llama mi tutor mi código es 123456', 'quién es mi tutor', 'dime el nombre de el profe tutor mi código es 123456', 'cómo se llama mi tutor del código 123456', 'quién es el tutor asignado soy el alumno 123456', 'busco a el tutor asignado mi código es 123456', 'quién es el profe tutor del código 123456', 'cómo se llama el profe tutor', 'dime el nombre de el profe tutor del código 123456', 'necesito contactar a el tutor asignado mi código es 123456', 'busco a mi tutor soy el alumno 123456', 'quién es mi tutor soy el alumno 123456', 'necesito contactar a el profe tutor soy el alumno 123456', 'busco a mi tutor mi código es 123456', 'cómo se llama el tutor asignado soy el alumno 123456', 'dime el nombre de el tutor asignado del código 123456', 'busco a el tutor asignado soy el alumno 123456', 'necesito contactar a mi tutor', 'busco a mi tutor del código 123456', 'cómo se llama mi tutor soy el alumno 123456', 'dime el nombre de mi tutor soy el alumno 123456', 'busco a el profe tutor', 'necesito contactar a el tutor asignado del código 123456', 'busco a el profe tutor soy el alumno 123456', 'cómo se llama el tutor asignado mi código es 123456', 'dime el nombre de mi tutor mi código es 123456', 'necesito contactar a el profe tutor del código 123456', 'cómo se llama el profe tutor mi código es 123456', 'quién es mi tutor del código 123456', 'busco a mi tutor', 'necesito contactar a mi tutor mi código es 123456', 'quién es el tutor asignado mi código es 123456', 'busco a el profe tutor del código 123456', 'cómo se llama mi tutor', 'necesito contactar a el tutor asignado']
        for i, caso in enumerate(casos):
            with self.subTest(caso=caso, idx=i):
                resultado = ChatbotEngine.obtener_respuesta(caso)
                self.assertEqual(resultado["categoria"], "Info_Tutor")

    def test_info_alumno(self):
        casos = ['dime de mi usuario soy 123456', 'dime de el alumno', 'cuáles son los datos de mi persona', 'dime de mi usuario código 123456', 'cuáles son los datos de el alumno código 123456', 'dime de mi persona', 'quién soy este estudiante mi código es 123456', 'información de el alumno código 123456', 'dime de este estudiante soy 123456', 'información de mi persona', 'quién soy el alumno', 'busca a este estudiante mi código es 123456', 'dime de este estudiante', 'información de mi persona código 123456', 'información de este estudiante código 123456', 'dime de el alumno código 123456', 'cuáles son los datos de este estudiante soy 123456', 'dime de este estudiante mi código es 123456', 'busca a el alumno mi código es 123456', 'quién soy mi usuario soy 123456', 'busca a mi persona código 123456', 'dime de mi persona soy 123456', 'cuáles son los datos de mi usuario código 123456', 'busca a mi usuario', 'cuáles son los datos de mi usuario', 'cuáles son los datos de mi persona mi código es 123456', 'información de este estudiante', 'información de el alumno', 'información de mi usuario soy 123456', 'dime de el alumno soy 123456', 'información de mi usuario mi código es 123456', 'quién soy mi persona', 'busca a mi usuario soy 123456', 'quién soy mi usuario código 123456', 'cuáles son los datos de mi usuario mi código es 123456', 'información de mi persona mi código es 123456', 'cuáles son los datos de mi persona código 123456', 'información de este estudiante mi código es 123456', 'cuáles son los datos de este estudiante mi código es 123456', 'quién soy mi persona soy 123456', 'quién soy mi persona código 123456', 'dime de el alumno mi código es 123456', 'busca a este estudiante soy 123456', 'quién soy este estudiante soy 123456', 'dime de mi persona mi código es 123456', 'cuáles son los datos de mi persona soy 123456', 'busca a mi usuario código 123456', 'dime de este estudiante código 123456', 'quién soy este estudiante código 123456', 'dime de mi usuario mi código es 123456']
        for i, caso in enumerate(casos):
            with self.subTest(caso=caso, idx=i):
                resultado = ChatbotEngine.obtener_respuesta(caso)
                self.assertEqual(resultado["categoria"], "Info_Alumno")

    def test_cursos_semestre(self):
        casos = ['dame la lista de cursos en el semestre IV', 'cuáles son las materias en el semestre 4', 'qué cursos hay para el nivel cuatro', 'qué cursos hay en el ciclo IV', 'cursos obligatorios para el nivel cuatro', 'cuáles son las materias para el nivel IV', 'qué cursos hay en el semestre cuatro', 'dame la lista de cursos en el ciclo quinto', 'dame la lista de cursos en el ciclo primero', 'dame la lista de cursos para el nivel 1', 'dame la lista de cursos para el nivel quinto', 'dame la lista de cursos para el nivel primero', 'qué cursos hay en el ciclo quinto', 'qué se enseña para el nivel primero', 'dame la lista de cursos en el semestre 5', 'dame la lista de cursos en el semestre quinto', 'cuáles son las materias en el ciclo quinto', 'cuáles son las materias para el nivel 4', 'qué se enseña en el ciclo 1', 'qué se enseña en el ciclo IV', 'dame la lista de cursos en el semestre 1', 'cuáles son las materias para el nivel 5', 'dame la lista de cursos en el ciclo IV', 'qué se enseña en el semestre 1', 'cuáles son las materias para el nivel quinto', 'qué cursos hay en el ciclo cuatro', 'qué se enseña en el semestre 4', 'dame la lista de cursos en el semestre 4', 'qué se enseña en el ciclo 5', 'cursos obligatorios en el semestre 4', 'qué se enseña para el nivel IV', 'cuáles son las materias en el semestre IV', 'dame la lista de cursos para el nivel cuatro', 'cursos obligatorios en el ciclo primero', 'cuáles son las materias en el ciclo cuatro', 'cuáles son las materias para el nivel primero', 'cuáles son las materias en el semestre quinto', 'cuáles son las materias en el ciclo 4', 'cuáles son las materias en el semestre 1', 'cursos obligatorios para el nivel 1', 'cuáles son las materias en el ciclo primero', 'cursos obligatorios en el semestre 1', 'qué cursos hay en el ciclo 1', 'qué se enseña para el nivel cuatro', 'qué se enseña en el semestre IV', 'qué se enseña para el nivel 5', 'qué se enseña para el nivel 1', 'qué cursos hay para el nivel 5', 'dame la lista de cursos para el nivel IV', 'qué cursos hay en el semestre 1']
        for i, caso in enumerate(casos):
            with self.subTest(caso=caso, idx=i):
                resultado = ChatbotEngine.obtener_respuesta(caso)
                self.assertEqual(resultado["categoria"], "Cursos_Semestre")

    def test_cursos_bloqueados(self):
        casos = ['qué pasa si repruebo Matemática', 'me bloquean algo si jalo Física', 'qué no puedo llevar si jalo Física', 'qué pasa si repruebo Programación', 'qué no puedo llevar si repruebo Programación', 'qué pasa si pierdo Física', 'qué cursos se me bloquean si repruebo Cálculo I', 'qué pasa si desapruebo Programación', 'qué pasa si biqueo Matemática', 'qué no puedo llevar si biqueo Física', 'qué cursos se me bloquean si pierdo Física', 'me bloquean algo si pierdo Cálculo I', 'qué pasa si biqueo Física', 'qué no puedo llevar si biqueo Programación', 'qué pasa si jalo Programación', 'me bloquean algo si jalo Programación', 'qué no puedo llevar si desapruebo Matemática', 'qué pasa si biqueo Cálculo I', 'me bloquean algo si biqueo Cálculo I', 'qué cursos se me bloquean si jalo Matemática', 'me bloquean algo si repruebo Programación', 'qué pasa si pierdo Matemática', 'qué cursos se me bloquean si biqueo Programación', 'me bloquean algo si desapruebo Física', 'qué cursos se me bloquean si biqueo Física', 'qué no puedo llevar si jalo Cálculo I', 'qué pasa si jalo Física', 'qué pasa si desapruebo Física', 'qué no puedo llevar si pierdo Matemática', 'me bloquean algo si jalo Matemática', 'qué no puedo llevar si pierdo Cálculo I', 'qué cursos se me bloquean si desapruebo Física', 'me bloquean algo si desapruebo Matemática', 'qué cursos se me bloquean si jalo Programación', 'qué cursos se me bloquean si biqueo Cálculo I', 'qué no puedo llevar si biqueo Cálculo I', 'qué no puedo llevar si jalo Programación', 'qué pasa si jalo Cálculo I', 'qué no puedo llevar si desapruebo Cálculo I', 'qué cursos se me bloquean si desapruebo Matemática', 'qué cursos se me bloquean si desapruebo Programación', 'me bloquean algo si jalo Cálculo I', 'me bloquean algo si pierdo Matemática', 'qué cursos se me bloquean si repruebo Matemática', 'qué pasa si pierdo Cálculo I', 'qué no puedo llevar si jalo Matemática', 'me bloquean algo si desapruebo Programación', 'qué pasa si biqueo Programación', 'qué cursos se me bloquean si repruebo Programación', 'qué pasa si repruebo Cálculo I']
        for i, caso in enumerate(casos):
            with self.subTest(caso=caso, idx=i):
                resultado = ChatbotEngine.obtener_respuesta(caso)
                self.assertIn(resultado["categoria"], ["Cursos_Bloqueados", "Reglamentos"])

    def test_info_curso_atributos(self):
        casos = ['de qué área es el curso de Cálculo II', 'es electivo la asignatura Redacción', 'vale la materia Cálculo II', 'cuántos créditos tiene la asignatura Redacción', 'es electivo la materia Ingeniería de Software', 'es electivo la asignatura Ingeniería de Software', 'vale la materia Redacción', 'vale la asignatura Cálculo II', 'qué tipo de curso es la asignatura Base de Datos', 'es electivo la materia Redacción', 'cuántos créditos tiene la asignatura Base de Datos', 'de qué área es el curso de Ingeniería de Software', 'qué tipo de curso es la materia Redacción', 'de qué área es la asignatura Base de Datos', 'qué tipo de curso es la materia Cálculo II', 'vale el curso de Base de Datos', 'cuántos créditos tiene el curso de Redacción', 'es electivo la asignatura Base de Datos', 'vale el curso de Cálculo II', 'cuántos créditos tiene la materia Ingeniería de Software', 'qué tipo de curso es la materia Base de Datos', 'cuántos créditos tiene la asignatura Cálculo II', 'vale la asignatura Redacción', 'es electivo la asignatura Cálculo II', 'de qué área es la materia Base de Datos', 'qué tipo de curso es el curso de Ingeniería de Software', 'cuántos créditos tiene el curso de Ingeniería de Software', 'de qué área es la asignatura Ingeniería de Software', 'qué tipo de curso es el curso de Base de Datos', 'vale la materia Ingeniería de Software', 'es electivo la materia Cálculo II', 'qué tipo de curso es la materia Ingeniería de Software', 'de qué área es el curso de Redacción', 'qué tipo de curso es el curso de Cálculo II', 'vale el curso de Ingeniería de Software', 'es electivo el curso de Ingeniería de Software', 'qué tipo de curso es la asignatura Redacción', 'de qué área es la materia Cálculo II', 'qué tipo de curso es la asignatura Ingeniería de Software', 'vale la materia Base de Datos', 'es electivo el curso de Base de Datos', 'de qué área es la asignatura Cálculo II', 'vale la asignatura Base de Datos', 'cuántos créditos tiene el curso de Cálculo II', 'qué tipo de curso es el curso de Redacción', 'de qué área es el curso de Base de Datos', 'cuántos créditos tiene la materia Base de Datos', 'qué tipo de curso es la asignatura Cálculo II', 'vale el curso de Redacción', 'de qué área es la materia Redacción']
        for i, caso in enumerate(casos):
            with self.subTest(caso=caso, idx=i):
                resultado = ChatbotEngine.obtener_respuesta(caso)
                self.assertIn(resultado["categoria"], ["Info_Curso_Atributos", "Reglamentos"])

    def test_rag_tramites(self):
        casos = ['cómo hago constancia de notas rápido', 'qué necesito para mi bachillerato', 'cuáles son los requisitos para mi bachillerato', 'cómo hago constancia de notas virtualmente', 'cuáles son los requisitos para constancia de notas virtualmente', 'cómo hago matrícula extemporánea', 'dónde tramito constancia de notas en la unsaac', 'cómo hago titulación virtualmente', 'cómo hago reserva de matrícula rápido', 'cuáles son los requisitos para reserva de matrícula', 'dónde tramito matrícula extemporánea', 'qué necesito para matrícula extemporánea en la unsaac', 'cómo hago reserva de matrícula', 'cuáles son los requisitos para reserva de matrícula virtualmente', 'cómo hago mi bachillerato virtualmente', 'qué necesito para mi bachillerato virtualmente', 'cuáles son los requisitos para titulación rápido', 'cómo hago reserva de matrícula en la unsaac', 'qué necesito para reserva de matrícula en la unsaac', 'dónde tramito mi bachillerato rápido', 'qué necesito para constancia de notas virtualmente', 'cómo hago matrícula extemporánea rápido', 'dónde tramito reserva de matrícula virtualmente', 'qué necesito para titulación', 'dónde tramito reserva de matrícula', 'cuáles son los requisitos para mi bachillerato en la unsaac', 'cómo hago mi bachillerato', 'cómo hago titulación', 'cuáles son los requisitos para matrícula extemporánea rápido', 'qué necesito para mi bachillerato rápido', 'cuáles son los requisitos para matrícula extemporánea en la unsaac', 'dónde tramito titulación', 'qué necesito para titulación rápido', 'dónde tramito mi bachillerato virtualmente', 'dónde tramito reserva de matrícula en la unsaac', 'cuáles son los requisitos para reserva de matrícula en la unsaac', 'cuáles son los requisitos para mi bachillerato virtualmente', 'cómo hago mi bachillerato en la unsaac', 'cuáles son los requisitos para titulación en la unsaac', 'dónde tramito titulación rápido', 'dónde tramito titulación virtualmente', 'qué necesito para mi bachillerato en la unsaac', 'qué necesito para matrícula extemporánea rápido', 'dónde tramito constancia de notas rápido', 'cómo hago matrícula extemporánea en la unsaac', 'cuáles son los requisitos para mi bachillerato rápido', 'qué necesito para titulación virtualmente', 'cómo hago reserva de matrícula virtualmente', 'dónde tramito constancia de notas virtualmente', 'cómo hago constancia de notas en la unsaac']
        for i, caso in enumerate(casos):
            with self.subTest(caso=caso, idx=i):
                resultado = ChatbotEngine.obtener_respuesta(caso)
                self.assertIn(resultado["categoria"], ["Tramites", "Reglamentos", "General"])

if __name__ == '__main__':
    unittest.main()
